### ISSUE TITLE
Autofac error when starting bus

### ISSUE THREAD

**Issue by Sphiecoh** [Particular/NServiceBus.Autofac#16]
I am getting the below error when starting the Bus :
`Method not found: 'Autofac.Builder.IRegistrationBuilder`3<!0,!1,!2> Autofac.Builder.IRegistrationBuilder`3.PropertiesAutowired(Autofac.PropertyWiringOptions)'.`

project.json looks like this :
``` "dependencies": {
    "Microsoft.AspNetCore.Hosting": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Online.Authentication.Handlers": "2.0.0-alpha-*",
    "Autofac.Extensions.DependencyInjection": "4.0.0-rc3-280",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "NServiceBus.Autofac": "5.0.0",
    "NServiceBus": "5.2.14",
    "Palantir.Mvc": "1.0.19",
    "Online.Mvc": "2.0.0-alpha-0022",
    "NServiceBus.Serilog": "2.0.1.1",
    "Serilog.Sinks.RollingFile":"2.1.0" 
  },
  "frameworks": {
    "net451": {}
  }```

My factory method looks like : 

public IBus CreateBus(IContainer container)
		{
			var busConfiguration = new BusConfiguration();
			busConfiguration.EndpointName(options.Endpoint);
			busConfiguration.UseSerialization<JsonSerializer>();
			busConfiguration.UsePersistence<InMemoryPersistence>();
			busConfiguration.UseContainer<AutofacBuilder>(c => c.ExistingLifetimeScope(container));

			if (Debugger.IsAttached)
				busConfiguration.EnableInstallers();
			busConfiguration.AssembliesToScan(typeof(ServiceBusHostOptions).Assembly, typeof(Authentication.Handlers.SmsEventHandler).Assembly, typeof(Authentication.Domain.Commands.Registration.RegisterUserCommand).Assembly , typeof(Handlers.SelfTestHandler).Assembly);

			return Bus.Create(busConfiguration).Start();
		}

**Comment by WilliamBZA** [comment]
Eita Sifiso! 

Looks like you're using .net core - which we don't officially support yet. Give me a day to try and repro your problem and I'll get back to you.

**Comment by Sphiecoh** [comment]
Yes but I am targeting .net451 which is full framework,

**Comment by WilliamBZA** [comment]
@Sphiecoh Found it. You're using Autofac version 4.0.0-rc3-280 and NServiceBus 5.2.14.

NServiceBus 5.2.14 has a maximum version dependency of Autofac < 4.0.0 which obviously does not match with the version of Autofac in your dependencies.  There are breaking changes between the V3 and V4 versions of the Autofac API so binding redirects wouldn't work here.

This means you'd have to downgrade Autofac to one of the V3.* versions.  Would you be able to do this?

We are waiting for autofac V4* to be out of RC before we officially support it in NServiceBus.

**Comment by Sphiecoh** [comment]
Let me try that but that will mean I cannot use `Autofac.Extensions.DependencyInjection` though I am not sure it is necessary to do this  :
```
var builder = new ContainerBuilder();
builder.Populate(services); <-- Is this required
```
seems to be copying dependencies from aspnet to autofac

**Comment by WilliamBZA** [comment]
Yeah it looks like that probably is.

You might be able to get away with simply doing [exactly what the method does under the covers](https://github.com/autofac/Autofac/blob/develop/src/Autofac.Extensions.DependencyInjection/AutofacRegistration.cs#L50)

I.e. Copying the file and including it as an extension method within your code.

Alternatively, what about one of the other containers? Or are you constrained to using Autofac?

**Comment by Sphiecoh** [comment]
Same problem with StructureMap:
StructureMap.Dnx ->structuremap (>= 4.0.0.266-alpha)
NServiceBus StructureMap  ->  StructureMap (>= 3.0.5.130 && < 4.0.0)

Is it possible to work without a container ?

**Comment by WilliamBZA** [comment]
Not currently. We're working slowly towards removing containers, but it's a slow process.

Did you perhaps try including the code from `AutofacRegistration.cs` into your project as an extension method?

**Comment by Sphiecoh** [comment]
that breaks  because it requires version 4.0.0 and NServiceBus.Autofac requires 3.5.0 :
```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'Autofac, Version=4.0.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Autofac, Version=3.5.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at Online.ServiceBus.Host.Startup.ConfigureServices(IServiceCollection services)
   --- End of inner exception stack trace ---
```

**Comment by danielmarbach** [comment]
@Sphiecoh @WilliamBZA meant literally copy pasting the method into your code

**Comment by Sphiecoh** [comment]
Thats what I did

**Comment by Sphiecoh** [comment]
Aaaah , just deleted then `bin` dir !!!! Its running now

**Comment by WilliamBZA** [comment]
Glad to hear it!

We'll keep monitoring Autofac, and once version 4 is officially released we'll our code to support it.
