### ISSUE TITLE
Can I use Child LifeTimeScope with NServiceBus?

### ISSUE THREAD

**Issue by gromy** [Particular/NServiceBus.Autofac#40]
I've registered some custom saga registrations in the root container and after creating new LifeTimeScope and path it in NServiceBus configuration it overrides my custom saga registrations and fails to resolve it in run time. When I use root container it works fine.
It means NServiceBus works only with root LifeTimeScope? Or it is a bug?

Autofac v4.3
NServiceBus v6.1.2
NServiceBus.Autofac v6.0.1

**Comment by WilliamBZA** [comment]
@gromy What do you mean by this?

> I've registered some custom saga registrations

What is a custom saga registration?

**Comment by gromy** [comment]
I need to make custom injection in any saga (last line actually contains some logic). 
Example:
allTypes.Where(x => x.IsEndingWith("Saga") && !x.IsAbstract && x.IsClass).ForEach(t =>
                    builder.RegisterType(t).WithParameter(new ResolvedParameter(
                        (p, c) =>
                                p.ParameterType == typeof(ICustomInjectionToSaga),
                        (p, c) =>
                                c.Resolve<ICustomInjectionToSaga>())));

**Comment by WilliamBZA** [comment]
@gromy I have a working repro now. Looks like a bug. I'll dig in and get back to you.

**Comment by WilliamBZA** [comment]
It seems there is an Autofac bug when using `ResolvedParameter`'s in combination with `BeginLifetimeScope` and `ContainerBuilder.Update()`.

See the following repro test:

```C#
class AutofacTest
{
    [Test]
    public void ResolvedParameters_Are_Copied_to_LifetimeScopes()
    {
        var builder = new ContainerBuilder();
        builder.RegisterType<TestParam>().As<IParam>();


        builder.RegisterType(typeof(TestClass)).WithParameter(new ResolvedParameter(
            (p, c) => p.ParameterType == typeof(TestParam),
            (p, c) => new SecondTestParam()
        ));

        var container = builder.Build();

        var childScope = container.BeginLifetimeScope();

        builder = new ContainerBuilder();
        builder.RegisterType<AutofacTest>();

        builder.Update(childScope.ComponentRegistry);

        var testClassRegistration = childScope.ComponentRegistry.Registrations.FirstOrDefault(r => r.Activator.LimitType == typeof(TestClass));

        Assert.NotNull(testClassRegistration);
    }
}
```

The instance of `testClassRegistration` is null at the end of the method, but is not null if the root container is queried.

It is also not null if `childScope.IsRegistered<TestClass>();` is called before the registry query.

I will raise a bug with the Autofac container but I have low hopes that they will fix it as they are pushing people to stop using the `ContainerBuilder.Update()` method - which we currently rely on quite heavily internally.

In the meantime a workaround for you might be to include the following just before starting your endpoint:

```C#
allTypes.Where(x => x.IsEndingWith("Saga") && !x.IsAbstract && x.IsClass).ForEach(t =>
{
    lifetimeScope.IsRegistered(t);
}); 
```

**Comment by WilliamBZA** [comment]
Sorry, I meant to ask if you could try the workaround and let me know if it works in the meantime for you 😄

**Comment by gromy** [comment]
Yeah, I tried to workaround moving custom saga registrations to the child LifeTimesSope and now it works. This is not a good solution but better then nothing =) 
Should I close the issue?

**Comment by WilliamBZA** [comment]
@gromy Did you try the workaround I posted? That should have worked without you having to do the registrations on the child container?

**Comment by gromy** [comment]
@WilliamBZA Sorry for late response, yeah, IsRegistered works too, thank you.

**Comment by WilliamBZA** [comment]
Great.

Then we've identified the bug with Autofac and have a workaround.

I'm going to close this, but will ping on this issue once Autofac have responded to the big.
