### ISSUE TITLE
Incorrect dependencies resolving inside child Autofac lifetime scope

### ISSUE THREAD

**Issue by alex-training** [Particular/NServiceBus.Autofac#48]
Hi guys!

I'm trying to host multiple NServiceBus endpoints in my custom self-written host, so I was thinking about creating a child Autofac lifetime scope per endpoint.

```
endpointConfiguration.UseContainer<AutofacBuilder>(
customizations: customizations =>
{
	customizations.ExistingLifetimeScope(_container.BeginLifetimeScope());
});
```

For some reason such approach doesn't work and I'm getting errors while resolving dependencies for my message handlers.

Probably I can use a root container everywhere instead, but I'm afraid about endpoints isolation.
Something like this:
```
endpointConfiguration.UseContainer<AutofacBuilder>(
customizations: customizations =>
{
	customizations.ExistingLifetimeScope(_rootContainer);
});
```

What I'm doing wrong?
Could you guys please help with some advice?

I've created a sample to demonstrate the issue:
[a sample](https://gitlab.com/alex_sk_/nsb_logging/blob/master/NSB_Logging/Program.cs#L35)

Many thanks

**Comment by WilliamBZA** [comment]
Hey @alex-training 

It seems to be related to how Modules are used within updated containers in child scopes. I'll let you know once i find something more concrete though

**Comment by WilliamBZA** [comment]
Yep, it appears that modules within child scopes are not handled as expected within autofac. Github issue [here](https://github.com/autofac/Autofac/issues/218).

I'm not sure we can do much ourselves here as this touches very deeply with autofac internals.

A quick fix is to re-register the module whenever you create a new livetimescope:

```CSharp
endpointConfiguration.UseContainer<AutofacBuilder>(
customizations: customizations =>
{
    var childScope = _container.BeginLifetimeScope(b => b.RegisterModule<NLogModule>());

    customizations.ExistingLifetimeScope(childScope); // THIS LINE DOESN'T WORK PROPERLY
    //customizations.ExistingLifetimeScope(_container); // THIS LINE WORKS
});
```

**Comment by alex-training** [comment]
Hey @WilliamBZA 
I've got it, thank you for your quick reply!

**Comment by WilliamBZA** [comment]
Great, I'm going to close this in the meantime.

By the way, we have [a sample](https://github.com/Particular/docs.particular.net/tree/master/samples/logging/nlog-custom/NLog_3) showing NLog integration that doesn't require an Autofac module. It uses a community port for NLog that @SimonCropp created.

**Comment by WilliamBZA** [comment]
Oops! It's not community port anymore, it's officially supported.

**Comment by alex-training** [comment]
Hi @WilliamBZA,

Tha's a cool sample, indeed.
However, later I would like to share and _inject_ an abstract ILogger interface via constructor injection.
