### ISSUE TITLE
Not sure that this works with generic HostBuilder/IServiceProviderFactory

### ISSUE THREAD

**Issue by dasjestyr** [Particular/NServiceBus.Autofac#60]
Forgive me, as I am finding it hard to explain. So the problem I'm running into is that in order to use Autofac, I do this in the NSB configuration:

``` csharp
builder.Populate(services); // Autofac.ContainerBuilder
endpointConfiguration.UseContainer<AutofacBuilder>(c => c.ExistingLifetimeScope(builder.Build()));
```
And in order to make sure this all stays in sync, I'd have to replace the service provider. In 2.0, I would change `public void ConfigureServices(...){ }` to `public IServiceProvider ConfigureServices(...){ }` and then make sure that new method returned an instance of `AutofacServiceProvider`:

``` csharp
public IServiceProvider ConfigureServices(IServiceCollection services) {
   // ... setup services
   builder.Populate(services);
   var container = builder.Build();
   endpointConfiguration.UseContainer<AutofacBuilder>(c => c.ExistingLifetimeScope(container));
   return new AutofacServiceProvider(container);
}
```

But now in 2.1 using the generic hosting builder, I need to use the `IServiceProviderFactory` for which Autofac provides `AutofacServiceProviderFactory()`:

``` csharp
new HostBuilder()
	.UseEnvironment(Environment.GetEnvironmentVariable("NETCORE_ENVIRONMENT") ?? "Development")
	.UseServiceProviderFactory(providerFactory)
	.ConfigureContainer<ContainerBuilder>((context, builder) =>
	{
		var config = context.Configuration;
		var environment = context.HostingEnvironment;
		var services = new ServiceCollection();

		// installers here
		services.AddCustomLogging(config, environment);
		services.AddRedis(config, environment);
		builder.Populate(services);
		services.AddNServiceBus(builder, config, environment);
	})
```

In `services.AddNServiceBus(builder, config, environment);` I'm only doing the `UseContainer` bit:

`endpointConfiguration.UseContainer<AutofacBuilder>(c => c.ExistingLifetimeScope(builder.Build()));`

The problem here is that because the AutofacServiceProviderFactory calls `.Build()` on the builder, and the `.UseContainer` on the endpoint configuration also requires me to call `.Build()`, it is being called twice which causes the container builder to throw because it can only be called once.

Is there a work around for this?

**Comment by WilliamBZA** [comment]
I haven't used the HostBuilder yet, but isn't there a way to call the `services.AddNServiceBus` method _after_ the `ConfigureContainer` method has completed? In other words, is there a way to use an instance of a `Container` instead of a `ContainerBuilder`?

**Comment by dasjestyr** [comment]
Maybe but I've not been able to find one. I believe the factory is what creates the instance of the container and it does so by calling `builder.Build()` internally. The problem is that `.AddNServiceBus()` also has to call builder.Build() in order to populate NSB's container. I'm not positive on the order everything gets called, so I don't really even have a suggestion at this juncture.

**Comment by WilliamBZA** [comment]
What about this:

```CSharp
new HostBuilder()
.UseEnvironment(Environment.GetEnvironmentVariable("NETCORE_ENVIRONMENT") ?? "Development")
.UseServiceProviderFactory(providerFactory)
.ConfigureContainer<ContainerBuilder>((context, builder) =>
{
	var config = context.Configuration;
	var environment = context.HostingEnvironment;
	var services = new ServiceCollection();

	// installers here
	services.AddCustomLogging(config, environment);
	services.AddRedis(config, environment);
	builder.Populate(services);

        builder.RegisterBuildCallback(container =>
        {
                services.AddNServiceBus(container, config, environment);
        });
});
```

Changing the `AddNServiceBus` method to accept an instance of IContainer instead of `ContainerBuilder`.  This way, that method is only invoked once there is an instance of `IContainer` already provided?

**Comment by dasjestyr** [comment]
interesting. going to try this now

**Comment by dasjestyr** [comment]
This seems to work! Thanks!
