### ISSUE TITLE
Incorrect Autofac dependencies on NServiceBus.Autofac 6 packages

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.Autofac#64]
The v6 packages of NServiceBus.Autofac state an autofac dependency of >= 4 && < 5: https://www.nuget.org/packages/NServiceBus.Autofac/6.0.1 but the [project is compiled against Autofac 4.2 ](https://github.com/Particular/NServiceBus.Autofac/blob/support-6.0/src/NServiceBus.Autofac/NServiceBus.Autofac.csproj#L55) which causes a dependency mismatch when trying to use autofac < 4.2 with NServiceBus.Autofac v6:

> Error	CS1705	Assembly 'NServiceBus.ObjectBuilder.Autofac' with identity 'NServiceBus.ObjectBuilder.Autofac, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' uses 'Autofac, Version=4.2.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da' which has a higher version than referenced assembly 'Autofac' with identity 'Autofac, Version=4.0.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da'

**Comment by timbussmann** [comment]
ping @Particular/container-maintainers

**Comment by boblangley** [comment]
@timbussmann Agreed this should be fixed, I have marked it `candidate-for-next-release` so it will be considered for the next containers maintenance release.

**Comment by timbussmann** [comment]
@boblangley are you thinking about updating the nuget package dependency or downgrading the referenced package?

**Comment by boblangley** [comment]
Downgrading the referenced package unless there is a good reason 4.2 must be the minimum, in which case we should just update the nuget package dependency.

**Comment by timbussmann** [comment]
this has been fixed as part of v7.
